# Generated by Django 2.2 on 2020-05-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='house_num',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_name',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
