# Generated by Django 2.2 on 2020-05-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200513_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=999)),
            ],
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserCountry'),
        ),
    ]
