# Generated by Django 2.2 on 2020-05-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200513_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='users.UserCountry'),
        ),
    ]
