# Generated by Django 2.2 on 2020-05-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200513_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercountry',
            old_name='country',
            new_name='country_name',
        ),
    ]
