# Generated by Django 2.2 on 2020-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='cvc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='exp_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='number',
            field=models.IntegerField(),
        ),
    ]
