# Generated by Django 2.2 on 2020-05-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200513_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
