# Generated by Django 2.2 on 2020-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_usercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('number', models.IntegerField()),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cvc', models.IntegerField()),
            ],
        ),
    ]
