# Generated by Django 2.2 on 2020-05-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='cvc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='exp_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='exp_year',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
