# Generated by Django 2.2 on 2020-05-15 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_useritemsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemsearch',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 10, 48, 29, 79201)),
            preserve_default=False,
        ),
    ]
