# Generated by Django 2.2 on 2020-05-14 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 15, 55, 42, 11592)),
        ),
    ]
