# Generated by Django 2.2 on 2020-05-14 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 15, 56, 51, 496077, tzinfo=utc)),
        ),
    ]
