# Generated by Django 2.2 on 2020-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_weekdays', models.CharField(max_length=255)),
                ('hours_saturday', models.CharField(max_length=255)),
                ('hours_sunday', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('social_facebook', models.CharField(max_length=255)),
                ('social_twitter', models.CharField(max_length=255)),
                ('social_youtube', models.CharField(max_length=255)),
                ('social_instagram', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
