# Generated by Django 2.2 on 2020-05-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200515_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='log',
            new_name='long',
        ),
    ]
