# Generated by Django 2.2 on 2020-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200515_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='zoom',
            field=models.CharField(max_length=255),
        ),
    ]
