# Generated by Django 2.2 on 2020-05-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200507_2045'),
        ('cart', '0002_auto_20200506_1306'),
    ]

    operations = [
    ]
